id = "mckeeman"
name = "McKeeman Form"
description = "McKeeman Form grammar support"
version = "0.0.1"
schema_version = 1
authors = ["Maksim Tomkavich <quendimax@gmail.com>"]
repository = "https://github.com/quendimax/zed-mckeeman"

[grammars.mckeeman]
repository = "https://github.com/quendimax/tree-sitter-mckeeman"
commit = "ab34e8db0b4c055031aae67caec3da80d4f7f376"
