name = "McKeeman Form"
grammar = "mckeeman"
path_suffixes = ["mkf"]
line_comment = [";"]
brackets = [
    { start="\"", end="\"", close=true, newline=false, not_in=["string", "singleton"] },
    { start="'", end="'", close=true, newline=false, not_in=["string", "singleton"] }
]
tab_size = 4
